/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ViewImport } from './routes/_view'
import { Route as AuthImport } from './routes/_auth'
import { Route as AdminImport } from './routes/_admin'
import { Route as AdminIndexImport } from './routes/_admin/index'
import { Route as AdminAboutImport } from './routes/_admin/about'
import { Route as AdminPostsIndexImport } from './routes/_admin/posts/index'
import { Route as AdminNotesIndexImport } from './routes/_admin/notes/index'
import { Route as ViewNotesIdImport } from './routes/_view/notes/$id'
import { Route as AuthAuthSignupImport } from './routes/_auth/auth/signup'
import { Route as AuthAuthSigninImport } from './routes/_auth/auth/signin'
import { Route as AdminSettingSettingImport } from './routes/_admin/setting/_setting'
import { Route as AdminSettingSettingIndexImport } from './routes/_admin/setting/_setting/index'
import { Route as AdminSettingSettingAboutImport } from './routes/_admin/setting/_setting/about'

// Create Virtual Routes

const AdminSettingImport = createFileRoute('/_admin/setting')()

// Create/Update Routes

const ViewRoute = ViewImport.update({
  id: '/_view',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const AdminSettingRoute = AdminSettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AdminRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAboutRoute = AdminAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)

const AdminPostsIndexRoute = AdminPostsIndexImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminNotesIndexRoute = AdminNotesIndexImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AdminRoute,
} as any)

const ViewNotesIdRoute = ViewNotesIdImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => ViewRoute,
} as any)

const AuthAuthSignupRoute = AuthAuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthSigninRoute = AuthAuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => AuthRoute,
} as any)

const AdminSettingSettingRoute = AdminSettingSettingImport.update({
  id: '/_setting',
  getParentRoute: () => AdminSettingRoute,
} as any)

const AdminSettingSettingIndexRoute = AdminSettingSettingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingSettingRoute,
} as any)

const AdminSettingSettingAboutRoute = AdminSettingSettingAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminSettingSettingRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_view': {
      id: '/_view'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ViewImport
      parentRoute: typeof rootRoute
    }
    '/_admin/about': {
      id: '/_admin/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AdminAboutImport
      parentRoute: typeof AdminImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/setting': {
      id: '/_admin/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AdminSettingImport
      parentRoute: typeof AdminImport
    }
    '/_admin/setting/_setting': {
      id: '/_admin/setting/_setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AdminSettingSettingImport
      parentRoute: typeof AdminSettingRoute
    }
    '/_auth/auth/signin': {
      id: '/_auth/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthSigninImport
      parentRoute: typeof AuthImport
    }
    '/_auth/auth/signup': {
      id: '/_auth/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_view/notes/$id': {
      id: '/_view/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof ViewNotesIdImport
      parentRoute: typeof ViewImport
    }
    '/_admin/notes/': {
      id: '/_admin/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AdminNotesIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/posts/': {
      id: '/_admin/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AdminPostsIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/setting/_setting/about': {
      id: '/_admin/setting/_setting/about'
      path: '/about'
      fullPath: '/setting/about'
      preLoaderRoute: typeof AdminSettingSettingAboutImport
      parentRoute: typeof AdminSettingSettingImport
    }
    '/_admin/setting/_setting/': {
      id: '/_admin/setting/_setting/'
      path: '/'
      fullPath: '/setting/'
      preLoaderRoute: typeof AdminSettingSettingIndexImport
      parentRoute: typeof AdminSettingSettingImport
    }
  }
}

// Create and export the route tree

interface AdminSettingSettingRouteChildren {
  AdminSettingSettingAboutRoute: typeof AdminSettingSettingAboutRoute
  AdminSettingSettingIndexRoute: typeof AdminSettingSettingIndexRoute
}

const AdminSettingSettingRouteChildren: AdminSettingSettingRouteChildren = {
  AdminSettingSettingAboutRoute: AdminSettingSettingAboutRoute,
  AdminSettingSettingIndexRoute: AdminSettingSettingIndexRoute,
}

const AdminSettingSettingRouteWithChildren =
  AdminSettingSettingRoute._addFileChildren(AdminSettingSettingRouteChildren)

interface AdminSettingRouteChildren {
  AdminSettingSettingRoute: typeof AdminSettingSettingRouteWithChildren
}

const AdminSettingRouteChildren: AdminSettingRouteChildren = {
  AdminSettingSettingRoute: AdminSettingSettingRouteWithChildren,
}

const AdminSettingRouteWithChildren = AdminSettingRoute._addFileChildren(
  AdminSettingRouteChildren,
)

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSettingRoute: typeof AdminSettingRouteWithChildren
  AdminNotesIndexRoute: typeof AdminNotesIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSettingRoute: AdminSettingRouteWithChildren,
  AdminNotesIndexRoute: AdminNotesIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthAuthSigninRoute: typeof AuthAuthSigninRoute
  AuthAuthSignupRoute: typeof AuthAuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthSigninRoute: AuthAuthSigninRoute,
  AuthAuthSignupRoute: AuthAuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ViewRouteChildren {
  ViewNotesIdRoute: typeof ViewNotesIdRoute
}

const ViewRouteChildren: ViewRouteChildren = {
  ViewNotesIdRoute: ViewNotesIdRoute,
}

const ViewRouteWithChildren = ViewRoute._addFileChildren(ViewRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof ViewRouteWithChildren
  '/about': typeof AdminAboutRoute
  '/': typeof AdminIndexRoute
  '/setting': typeof AdminSettingSettingRouteWithChildren
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/notes/$id': typeof ViewNotesIdRoute
  '/notes': typeof AdminNotesIndexRoute
  '/posts': typeof AdminPostsIndexRoute
  '/setting/about': typeof AdminSettingSettingAboutRoute
  '/setting/': typeof AdminSettingSettingIndexRoute
}

export interface FileRoutesByTo {
  '': typeof ViewRouteWithChildren
  '/about': typeof AdminAboutRoute
  '/': typeof AdminIndexRoute
  '/setting': typeof AdminSettingSettingIndexRoute
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/notes/$id': typeof ViewNotesIdRoute
  '/notes': typeof AdminNotesIndexRoute
  '/posts': typeof AdminPostsIndexRoute
  '/setting/about': typeof AdminSettingSettingAboutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_view': typeof ViewRouteWithChildren
  '/_admin/about': typeof AdminAboutRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/setting': typeof AdminSettingRouteWithChildren
  '/_admin/setting/_setting': typeof AdminSettingSettingRouteWithChildren
  '/_auth/auth/signin': typeof AuthAuthSigninRoute
  '/_auth/auth/signup': typeof AuthAuthSignupRoute
  '/_view/notes/$id': typeof ViewNotesIdRoute
  '/_admin/notes/': typeof AdminNotesIndexRoute
  '/_admin/posts/': typeof AdminPostsIndexRoute
  '/_admin/setting/_setting/about': typeof AdminSettingSettingAboutRoute
  '/_admin/setting/_setting/': typeof AdminSettingSettingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/'
    | '/setting'
    | '/auth/signin'
    | '/auth/signup'
    | '/notes/$id'
    | '/notes'
    | '/posts'
    | '/setting/about'
    | '/setting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/about'
    | '/'
    | '/setting'
    | '/auth/signin'
    | '/auth/signup'
    | '/notes/$id'
    | '/notes'
    | '/posts'
    | '/setting/about'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_view'
    | '/_admin/about'
    | '/_admin/'
    | '/_admin/setting'
    | '/_admin/setting/_setting'
    | '/_auth/auth/signin'
    | '/_auth/auth/signup'
    | '/_view/notes/$id'
    | '/_admin/notes/'
    | '/_admin/posts/'
    | '/_admin/setting/_setting/about'
    | '/_admin/setting/_setting/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ViewRoute: typeof ViewRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ViewRoute: ViewRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_admin",
        "/_auth",
        "/_view"
      ]
    },
    "/_admin": {
      "filePath": "_admin.tsx",
      "children": [
        "/_admin/about",
        "/_admin/",
        "/_admin/setting",
        "/_admin/notes/",
        "/_admin/posts/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth/signin",
        "/_auth/auth/signup"
      ]
    },
    "/_view": {
      "filePath": "_view.tsx",
      "children": [
        "/_view/notes/$id"
      ]
    },
    "/_admin/about": {
      "filePath": "_admin/about.tsx",
      "parent": "/_admin"
    },
    "/_admin/": {
      "filePath": "_admin/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/setting": {
      "filePath": "_admin/setting",
      "parent": "/_admin",
      "children": [
        "/_admin/setting/_setting"
      ]
    },
    "/_admin/setting/_setting": {
      "filePath": "_admin/setting/_setting.tsx",
      "parent": "/_admin/setting",
      "children": [
        "/_admin/setting/_setting/about",
        "/_admin/setting/_setting/"
      ]
    },
    "/_auth/auth/signin": {
      "filePath": "_auth/auth/signin.tsx",
      "parent": "/_auth"
    },
    "/_auth/auth/signup": {
      "filePath": "_auth/auth/signup.tsx",
      "parent": "/_auth"
    },
    "/_view/notes/$id": {
      "filePath": "_view/notes/$id.tsx",
      "parent": "/_view"
    },
    "/_admin/notes/": {
      "filePath": "_admin/notes/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/posts/": {
      "filePath": "_admin/posts/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/setting/_setting/about": {
      "filePath": "_admin/setting/_setting/about.tsx",
      "parent": "/_admin/setting/_setting"
    },
    "/_admin/setting/_setting/": {
      "filePath": "_admin/setting/_setting/index.tsx",
      "parent": "/_admin/setting/_setting"
    }
  }
}
ROUTE_MANIFEST_END */
